version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # - data01:/usr/share/elasticsearch/data
      # - ./es01:/usr/share/elasticsearch/data
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  nginx:
    image: derciosinione/ngnix-beats:latest
    container_name: nginx-beats
    build: ./nginx
    volumes:
      - nginx-data:/nginxdata
    ports:
      - 9000:80

volumes:
  elasticsearch-data:
    driver: local
  nginx-data:
    driver: local
